--test-data.sql

 INSERT INTO POT (COL, ROW, CAPACITY, NOTE) VALUES (1, 1, 2, 'test pot');

-- INSERT INTO TREE (NAME, TREETYPE) VALUES ('Tuja','List');
INSERT INTO trees (NAME, TREETYPE, ISPROTECTED) VALUES ('Tuja','List', FALSE );
